# Generated by Django 5.0.7 on 2025-01-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/blogging-e5f0c.appspot.com/o/blogImages%2FdefaultImage.jpg?alt=media&token=aea70a20-64fd-4a89-9669-8e1b5b8fe8c9', max_length=500),
        ),
    ]
